#%RAML 1.0 Trait
description: "these common header are used for bussiness Enpoints to know the consumer details of an API"

headers:
  ion_sourcesystem:
    type: string
    description: Identifier for source system invoking the API
    example: saleforce
  ion_sourcesubsystem: 
    type: string
    description: Identifier for source system invoking the API
    example: saleforce worker table

      