#%RAML 1.0 SecurityScheme
type: x-ion-clientIdEnforcement
describedBy:
  headers:
    ion_client_id:
      type: string
      example: "x4avd84v8ad5da5v48a"
    ion_client_secret:
      type: string
      example: "d5sa4d8sa4fas1c8a5s"
